// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efhhyvduutpyyafqkdrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmaGh5dmR1dXRweXlhZnFrZHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDAwMzksImV4cCI6MjA2NjcxNjAzOX0.V3Fwz2YaDtOZRf6lkvyD-7iN69Plp0YJWurqnaKWwwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
